# Generated by Django 4.2.14 on 2024-07-15 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SexTitleFull', models.CharField(max_length=50, verbose_name='Полное название пола')),
                ('SexTitleShort', models.CharField(max_length=10, verbose_name='Короткое название пола')),
                ('IsActive', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TreatmentTypeTitle', models.CharField(max_length=20, verbose_name='Статус человека')),
                ('IsActive', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonFirstName', models.CharField(max_length=100, verbose_name='Имя')),
                ('PersonSecondName', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('PersonLastName', models.CharField(max_length=100, verbose_name='Отчество')),
                ('PersonDataBirth', models.DateField(verbose_name='Дата рождения')),
                ('IsActive', models.BooleanField(default=True, verbose_name='Активный')),
                ('SexID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.sex', verbose_name='Пол')),
                ('TreatmentTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.treatmenttype', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Человк',
                'verbose_name_plural': 'Люди',
            },
        ),
    ]
