# Generated by Django 4.2.14 on 2024-07-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentSeries', models.CharField(max_length=100, verbose_name='Серия документа')),
                ('DocumentNumber', models.CharField(max_length=100, verbose_name='Номер документа')),
                ('DocumentNumberAdditional', models.CharField(max_length=100, verbose_name='Дополнительный номер документа')),
                ('DocumentDateIssue', models.DateField(verbose_name='Дата выдачи документа')),
                ('DocumentIssuerOfficial', models.CharField(max_length=200, verbose_name='Официальный эмитент документа')),
                ('DocumentIssuerAdditionalNotes', models.CharField(max_length=200, verbose_name='Дополнительная информация о документе')),
                ('DocumentDateExpire', models.DateField(verbose_name='Дата истечения срока давности документа')),
                ('IsActive', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentCategoryTitle', models.CharField(max_length=100, verbose_name='Название категории документа')),
                ('DocumentCategoryNotes', models.CharField(max_length=500, verbose_name='Примечания для категории документа')),
                ('IsActive', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Категория документа',
                'verbose_name_plural': 'Категории документов',
            },
        ),
        migrations.CreateModel(
            name='PersonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonID', models.IntegerField(verbose_name='Человек')),
                ('PersonDocumentDateInput', models.DateField(verbose_name='Дата составления документа')),
                ('InputDataNotes', models.CharField(max_length=500, verbose_name='Примечания даты составления')),
                ('IsActive', models.BooleanField(default=True, verbose_name='Активный')),
                ('DocumentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.document', verbose_name='Номер документа')),
            ],
            options={
                'verbose_name': 'Документ подтверждающий личность',
                'verbose_name_plural': 'Документы подтверждающие личность',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentTypeTitleFull', models.CharField(max_length=100, verbose_name='Полное название типа документа')),
                ('DocumentTypeTitleShort', models.CharField(max_length=20, verbose_name='Короткое название типа документа')),
                ('DocumentTypeNotes', models.CharField(max_length=500, verbose_name='Примечания для типа документа')),
                ('CountryID', models.IntegerField(verbose_name='Страна')),
                ('IsActive', models.BooleanField(default=True, verbose_name='Активный')),
                ('DocumentCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.documentcategory', verbose_name='Категория документа')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='DocumentTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.documenttype', verbose_name='Номер типа документа'),
        ),
    ]
